
cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

secretsibmcloud:
  enabled: false
  imagePullSecrets: image-pull-secret-ibm-cloud

service:
  name: {{ .ServiceName }}
  type: LoadBalancer
  externalPort: {{ .LBPort }}
  containerPort: {{ .ContainerPort }}
  nodePort: 31070
  replicaCount: 1

  GITACCOUNT:
  APITOKEN:
  GITREPO: "github.com/lj020326/config-data.git"

  CONFIGFILE: services
  Release: "{{ .Release }}"
  Environment: "{{ .Env }}"
  K8s_namespace: "{{ .Kube_namespace }}"
  APIVER: "{{ .ApiVer }}"
  #NodeSelector: services

image:
  repository: "{{ .DockerOrg }}/{{ .ServiceName }}:{{ .Release }}"
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 100Mi
